print ('hello world')
print ("python and git")
a = input ("input your last name: ")
print (f"welcome {a} Hello again GitHub")
id = input ("Please input your id: ")
print (f"Your {id} will be processed")